// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using car_shop.infra;

#nullable disable

namespace car_shop.infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241017105257_AddMoreCarModels")]
    partial class AddMoreCarModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("car_shop.domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "BMW",
                            Model = "330i",
                            Price = 30000.0,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Make = "Audi",
                            Model = "A4",
                            Price = 28000.0,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Make = "Mercedes-Benz",
                            Model = "C-Class",
                            Price = 32000.0,
                            Stock = 8
                        },
                        new
                        {
                            Id = 4,
                            Make = "Tesla",
                            Model = "Model 3",
                            Price = 40000.0,
                            Stock = 12
                        },
                        new
                        {
                            Id = 5,
                            Make = "Ford",
                            Model = "Mustang",
                            Price = 35000.0,
                            Stock = 6
                        },
                        new
                        {
                            Id = 6,
                            Make = "Honda",
                            Model = "Civic",
                            Price = 22000.0,
                            Stock = 20
                        },
                        new
                        {
                            Id = 7,
                            Make = "Toyota",
                            Model = "Corolla",
                            Price = 21000.0,
                            Stock = 18
                        },
                        new
                        {
                            Id = 8,
                            Make = "Volkswagen",
                            Model = "Golf",
                            Price = 25000.0,
                            Stock = 14
                        },
                        new
                        {
                            Id = 9,
                            Make = "Chevrolet",
                            Model = "Camaro",
                            Price = 37000.0,
                            Stock = 5
                        },
                        new
                        {
                            Id = 10,
                            Make = "Nissan",
                            Model = "Altima",
                            Price = 23000.0,
                            Stock = 16
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
